-- pim schema step 1, as introduced at 087d09de on 2026-08-15
-- The PIM store: one file for every calendar, task list, note list and address book
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE collections (
            id            INTEGER PRIMARY KEY,
            account       TEXT    NOT NULL DEFAULT '',        -- the DAV account's address; '' for a local collection
            kind          TEXT    NOT NULL CHECK (kind IN ('vevent', 'vtodo', 'vjournal', 'vcard')),
            display_name  TEXT    NOT NULL,
            color         TEXT    NOT NULL DEFAULT '',        -- a category token or #RRGGBB
            dav_url       TEXT,
            ctag          TEXT,
            sync_token    TEXT,
            is_visible    INTEGER NOT NULL DEFAULT 1,
            is_readonly   INTEGER NOT NULL DEFAULT 0,
            is_default    INTEGER NOT NULL DEFAULT 0,
            ordinal       INTEGER NOT NULL DEFAULT 0,
            created_utc   INTEGER NOT NULL
        );

        CREATE TABLE pim_items (
            id               INTEGER PRIMARY KEY,
            collection_id    INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
            uid              TEXT    NOT NULL,
            kind             TEXT    NOT NULL,
            dav_href         TEXT,
            etag             TEXT,
            raw_payload      TEXT    NOT NULL,                -- the iCalendar / vCard text, verbatim
            summary          TEXT    NOT NULL DEFAULT '',
            description      TEXT    NOT NULL DEFAULT '',
            location         TEXT    NOT NULL DEFAULT '',
            starts_utc       INTEGER,                        -- unix seconds; the first occurrence for a series
            ends_utc         INTEGER,
            starts_local     TEXT,                           -- yyyy-MM-ddTHH:mm:ss, the wall time as written
            ends_local       TEXT,
            tz_id            TEXT,                           -- IANA zone of the wall time, or NULL for floating / UTC
            all_day          INTEGER NOT NULL DEFAULT 0,
            status           TEXT    NOT NULL DEFAULT '',
            priority         INTEGER NOT NULL DEFAULT 0,
            percent_complete INTEGER NOT NULL DEFAULT 0,
            completed_utc    INTEGER,
            rrule            TEXT,                           -- the RRULE line, when the item repeats
            recurrence_id    TEXT,                           -- for an override: which occurrence it replaces
            is_override      INTEGER NOT NULL DEFAULT 0,
            sequence         INTEGER NOT NULL DEFAULT 0,
            organizer        TEXT    NOT NULL DEFAULT '',
            busy             TEXT    NOT NULL DEFAULT 'busy',-- free | tentative | busy | oof
            reminder_minutes INTEGER,                        -- VALARM trigger before the start, or NULL
            categories       TEXT    NOT NULL DEFAULT '',    -- comma-separated category names
            last_modified    INTEGER NOT NULL,
            sync_state       TEXT    NOT NULL DEFAULT 'synced' -- synced | new | modified | deleted (a local change the server has not seen)
        );

        CREATE INDEX pim_items_collection ON pim_items(collection_id, starts_utc);
        CREATE INDEX pim_items_uid ON pim_items(collection_id, uid, recurrence_id);

        CREATE TABLE pim_attendees (
            item_id   INTEGER NOT NULL REFERENCES pim_items(id) ON DELETE CASCADE,
            address   TEXT    NOT NULL,
            name      TEXT    NOT NULL DEFAULT '',
            role      TEXT    NOT NULL DEFAULT '',
            partstat  TEXT    NOT NULL DEFAULT '',
            rsvp      INTEGER NOT NULL DEFAULT 0,
            ordinal   INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE dav_queue (
            id             INTEGER PRIMARY KEY,
            collection_id  INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
            item_id        INTEGER,
            op             TEXT    NOT NULL CHECK (op IN ('put', 'delete')),
            state          TEXT    NOT NULL DEFAULT 'queued',
            attempts       INTEGER NOT NULL DEFAULT 0,
            last_error     TEXT,
            created_utc    INTEGER NOT NULL
        );

        CREATE VIRTUAL TABLE pim_fts USING fts5(
            summary, description, location, attendees,
            tokenize='unicode61 remove_diacritics 2'
        );
