-- pim schema step 2, as introduced at 5e5ab9d0 on 2026-08-16
-- The Calendar module: four views drawn to the captures, the DAV engine behind them, and iMIP
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE pim_items ADD COLUMN reminder_dismissed_utc INTEGER;
        ALTER TABLE pim_items ADD COLUMN reminder_snoozed_utc INTEGER;
