-- pim schema step 3, as introduced at 27562f36 on 2026-08-16
-- Contacts in the store: columns to draw a list from, and the card underneath
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE pim_items ADD COLUMN file_as    TEXT    NOT NULL DEFAULT '';
        ALTER TABLE pim_items ADD COLUMN first_name TEXT    NOT NULL DEFAULT '';
        ALTER TABLE pim_items ADD COLUMN last_name  TEXT    NOT NULL DEFAULT '';
        ALTER TABLE pim_items ADD COLUMN company    TEXT    NOT NULL DEFAULT '';
        ALTER TABLE pim_items ADD COLUMN job_title  TEXT    NOT NULL DEFAULT '';
        ALTER TABLE pim_items ADD COLUMN is_group   INTEGER NOT NULL DEFAULT 0;

        CREATE INDEX pim_items_filed ON pim_items(collection_id, file_as);

        CREATE TABLE pim_contact_fields (
            item_id  INTEGER NOT NULL REFERENCES pim_items(id) ON DELETE CASCADE,
            kind     TEXT    NOT NULL CHECK (kind IN ('email', 'phone', 'im')),
            value    TEXT    NOT NULL,
            label    TEXT    NOT NULL DEFAULT '',   -- business | home | mobile | businessfax | ...
            ordinal  INTEGER NOT NULL DEFAULT 0
        );

        CREATE INDEX pim_contact_fields_item ON pim_contact_fields(item_id);
        CREATE INDEX pim_contact_fields_value ON pim_contact_fields(kind, value);

        CREATE TABLE pim_photos (
            item_id    INTEGER PRIMARY KEY REFERENCES pim_items(id) ON DELETE CASCADE,
            media_type TEXT NOT NULL DEFAULT 'image/jpeg',
            bytes      BLOB NOT NULL
        );
