-- pim schema step 4, as introduced at 2431e049 on 2026-08-16
-- One set of colour categories, across every module
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE categories (
            id           INTEGER PRIMARY KEY,
            name         TEXT    NOT NULL,
            colour_token TEXT    NOT NULL,
            shortcut     TEXT,
            ordinal      INTEGER NOT NULL DEFAULT 0
        );

        CREATE UNIQUE INDEX categories_name ON categories(name COLLATE NOCASE);
