-- pim schema step 5, as introduced at 8f37b261 on 2026-08-17
-- The Tasks bar's tags: Flag Task, Private and the two Importance buttons
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE pim_items ADD COLUMN is_private INTEGER NOT NULL DEFAULT 0;
