-- pim schema step 6, as introduced at 868b766c on 2026-08-17
-- Private and Follow Up on a contact, and one flag menu for both
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE pim_items ADD COLUMN follow_up_due      INTEGER;
        ALTER TABLE pim_items ADD COLUMN follow_up_complete INTEGER NOT NULL DEFAULT 0;
