-- pim schema step 7, as introduced at db442f4f on 2026-08-23
-- The People list shows a linked pair as one person
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE pim_items ADD COLUMN links TEXT NOT NULL DEFAULT '';
