-- pim schema step 8, as introduced at 2e0b26ce on 2026-08-25
-- A subscribed calendar was never going to fill, and now it does
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE collections ADD COLUMN last_checked_utc INTEGER;
