using System.Text;
using Mailbox.Core.Commands;

namespace Mailbox.Tests;

/// <summary>
/// Writes the press sweep's pose list from the registered catalogue itself. Skipped in an
/// ordinary run; set <c>MAILBOX_PRESS_LIST</c> to a path to produce one.
/// </summary>
/// <remarks>
/// The sweep's question is the owner's: which buttons, pressed, do nothing? The static sweeps
/// prove every command is described and chorded; the enablement tests prove the declarations are
/// consistent; nothing presses them. This list makes <c>tools/audit-run.sh</c> do exactly that —
/// one pose per command, in the module the command belongs to, with a selection posed and the
/// clock pinned, each classified afterwards from the settled read-back the run door logs.
/// <para>
/// The list is generated rather than written, so a command added to the catalogue is in the
/// sweep the next time it runs, and a set added to the application fails the coverage assertion
/// below rather than going quietly unswept. The three item-window sets — compose, contact,
/// appointment — are skipped by name: their commands live in windows the shell's dispatcher
/// does not reach, and sweeping those surfaces needs run doors of their own first.
/// </para>
/// </remarks>
public class PressSweepList
{
    /// <summary>The sets the shell's dispatcher reaches, with the module each is pressed in.</summary>
    private static readonly (string Module, IEnumerable<MailboxCommand> Commands, string Name)[] Swept =
    [
        ("mail", MailCommands.All, nameof(MailCommands)),
        ("mail", ViewCommands.All, nameof(ViewCommands)),
        ("calendar", CalendarCommands.All, nameof(CalendarCommands)),
        ("people", PeopleCommands.All, nameof(PeopleCommands)),
        ("tasks", TaskCommands.All, nameof(TaskCommands)),
        ("notes", NoteCommands.All, nameof(NoteCommands)),
        ("journal", JournalCommands.All, nameof(JournalCommands)),
        ("feeds", FeedCommands.All, nameof(FeedCommands)),
    ];

    /// <summary>The sets that live in item windows, skipped until those windows have a run door.</summary>
    private static readonly string[] SkippedByName =
        [nameof(ComposeCommands), nameof(ContactCommands), nameof(AppointmentCommands)];

    /// <summary>
    /// The two subscriptions whose folders <c>SeedHarness.SeedFeedsStore</c> builds, as the
    /// settings JSON the pose injects — names and categories must match the seeded tree or the
    /// workspace maps them to nothing.
    /// </summary>
    private const string SeededSubscriptions =
        "[{\"url\":\"https://example.invalid/ars\",\"name\":\"Ars Technica\",\"category\":\"Technology\"},"
        + "{\"url\":\"https://example.invalid/bbc\",\"name\":\"BBC News\",\"category\":\"News\"}]";

    /// <summary>
    /// Every command set the assembly declares is either swept or skipped by name — a new set
    /// cannot go quietly unswept.
    /// </summary>
    [Fact]
    public void EveryCommandSetIsSweptOrSkippedByName()
    {
        var declared = typeof(MailCommands).Assembly.GetTypes()
            .Where(t => t is { IsAbstract: true, IsSealed: true }
                        && t.Namespace == typeof(MailCommands).Namespace
                        && t.Name.EndsWith("Commands", StringComparison.Ordinal))
            .Select(t => t.Name)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var covered = Swept.Select(s => s.Name).Concat(SkippedByName)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        Assert.Equal(declared, covered);
    }

    [Fact]
    public void WriteOnRequest()
    {
        if (Environment.GetEnvironmentVariable("MAILBOX_PRESS_LIST") is not { Length: > 0 } path) return;

        var list = new StringBuilder();
        list.AppendLine("# The press sweep: one pose per shell-reachable command, generated by");
        list.AppendLine("# PressSweepList.WriteOnRequest — regenerate rather than edit. The item-window");
        list.AppendLine($"# sets ({string.Join(", ", SkippedByName)}) wait on run doors of their own.");

        foreach (var (module, commands, _) in Swept)
        {
            foreach (var command in commands)
            {
                // Tab-separated pairs, which is the runner's format for a value carrying a
                // space — the feeds subscriptions carry several. wait-1500 lets the posed
                // module switch and selection land first; the press itself then reports the
                // settled read-back the classifier reads.
                // People's selection door names a person, and the seed has one; the other
                // module lists keep their guards, which the expectations record as verified.
                var select = module == "people" ? "A. Person" : "1";

                var pairs = new List<string>
                {
                    $"MAILBOX_MODULE={module}",
                    $"MAILBOX_SELECT={select}",
                    "MAILBOX_TODAY=2026-08-16",
                };

                // The feeds poses carry the two subscriptions whose folders the seed builds,
                // so the module opens onto articles rather than an empty pane.
                if (module == "feeds") pairs.Add($"MAILBOX_SETTING=rss.feeds={SeededSubscriptions}");

                pairs.Add($"MAILBOX_RUN=wait-1500,{command.Id.Value}");

                list.AppendLine($"press-{command.Id.Value}\t" + string.Join('\t', pairs));
            }
        }

        File.WriteAllText(path, list.ToString());
    }
}
