-- mail schema step 1, as introduced at 6447bd7f on 2026-08-14
-- Begin Phase 2 with the store the rest of it needs
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE accounts (
            id            INTEGER PRIMARY KEY,
            address       TEXT    NOT NULL UNIQUE,
            display_name  TEXT    NOT NULL DEFAULT '',
            protocol      TEXT    NOT NULL CHECK (protocol IN ('pop3', 'imap')),
            ordinal       INTEGER NOT NULL DEFAULT 0,
            created_utc   INTEGER NOT NULL
        );

        CREATE TABLE folders (
            id            INTEGER PRIMARY KEY,
            account_id    INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
            parent_id     INTEGER          REFERENCES folders(id)  ON DELETE CASCADE,
            name          TEXT    NOT NULL,
            -- Inbox, Sent, Drafts and so on, so the shell can find them without matching names
            -- in whatever language the server speaks.
            role          TEXT    NOT NULL DEFAULT 'none',
            ordinal       INTEGER NOT NULL DEFAULT 0,
            UNIQUE (account_id, parent_id, name)
        );

        -- Raw RFC822, kept verbatim and separately from the parsed columns. Every header we
        -- decided not to parse is still in here, which is what makes a later reparse possible.
        CREATE TABLE blobs (
            id            INTEGER PRIMARY KEY,
            bytes         BLOB    NOT NULL,
            byte_length   INTEGER NOT NULL,
            compression   TEXT    NOT NULL DEFAULT 'none'
        );

        CREATE TABLE messages (
            id            INTEGER PRIMARY KEY,
            folder_id     INTEGER NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
            blob_id       INTEGER          REFERENCES blobs(id),
            -- The server's own identity for the message: POP3 UIDL, IMAP UID. Unique per
            -- folder, and the thing that stops a re-poll duplicating everything.
            server_uid    TEXT,
            message_id    TEXT,
            in_reply_to   TEXT,
            thread_key    TEXT,
            from_name     TEXT    NOT NULL DEFAULT '',
            from_address  TEXT    NOT NULL DEFAULT '',
            subject       TEXT    NOT NULL DEFAULT '',
            preview       TEXT    NOT NULL DEFAULT '',
            sent_utc      INTEGER,
            received_utc  INTEGER NOT NULL,
            size_bytes    INTEGER NOT NULL DEFAULT 0,
            is_read       INTEGER NOT NULL DEFAULT 0,
            is_flagged    INTEGER NOT NULL DEFAULT 0,
            has_attachment INTEGER NOT NULL DEFAULT 0,
            UNIQUE (folder_id, server_uid)
        );

        CREATE INDEX messages_by_folder_date ON messages (folder_id, received_utc DESC);
        CREATE INDEX messages_by_thread      ON messages (thread_key);
        CREATE INDEX messages_by_message_id  ON messages (message_id);
        CREATE INDEX folders_by_account      ON folders  (account_id, ordinal);
