-- mail schema step 2, as introduced at 6447bd7f on 2026-08-14
-- Begin Phase 2 with the store the rest of it needs
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        -- External-content FTS: the index stores no copy of the text, it points back at
        -- messages. Halves the store's size and makes the index impossible to leave stale,
        -- because there is only one copy of the data.
        CREATE VIRTUAL TABLE messages_fts USING fts5 (
            subject,
            from_name,
            from_address,
            preview,
            body,
            content = 'messages',
            content_rowid = 'id',
            tokenize = 'unicode61 remove_diacritics 2'
        );

        CREATE TRIGGER messages_fts_insert AFTER INSERT ON messages BEGIN
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, '');
        END;

        CREATE TRIGGER messages_fts_delete AFTER DELETE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, '');
        END;

        CREATE TRIGGER messages_fts_update AFTER UPDATE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, '');
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, '');
        END;
