-- mail schema step 3, as introduced at 6447bd7f on 2026-08-14
-- Begin Phase 2 with the store the rest of it needs
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        -- Sending is a queue with its own state, not a method call. A message that failed to
        -- send has to survive the process that failed to send it, and has to say why.
        CREATE TABLE outbox (
            id            INTEGER PRIMARY KEY,
            account_id    INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
            blob_id       INTEGER NOT NULL REFERENCES blobs(id),
            state         TEXT    NOT NULL DEFAULT 'queued'
                          CHECK (state IN ('queued', 'sending', 'sent', 'failed', 'held')),
            attempts      INTEGER NOT NULL DEFAULT 0,
            queued_utc    INTEGER NOT NULL,
            next_try_utc  INTEGER,
            last_error    TEXT
        );

        CREATE INDEX outbox_by_state ON outbox (state, next_try_utc);
