-- mail schema step 4, as introduced at 54c1e9c2 on 2026-08-14
-- Build out account settings
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        -- Which account new mail is sent from when nothing else decides. A column rather than a
        -- setting, because it has to be true of exactly one account and the database can say so.
        ALTER TABLE accounts ADD COLUMN is_default INTEGER NOT NULL DEFAULT 0;

        -- The first account is the default until told otherwise.
        UPDATE accounts SET is_default = 1
        WHERE id = (SELECT id FROM accounts ORDER BY ordinal, id LIMIT 1);

        CREATE UNIQUE INDEX one_default_account ON accounts (is_default) WHERE is_default = 1;
