-- mail schema step 5, as introduced at d70a5603 on 2026-08-14
-- Give every account its own store file
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        -- Each account now has its own store file, so a file holds exactly one account and
        -- "which is the default" is a question about the set of files rather than about any
        -- one of them. It lives in the settings file instead; a column here could only ever
        -- describe this file, and two files could both claim it with nothing to notice.
        DROP INDEX IF EXISTS one_default_account;
        ALTER TABLE accounts DROP COLUMN is_default;
