-- mail schema step 6, as introduced at 42fb9f49 on 2026-08-14
-- Finish Phase 3, and say plainly what is left
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        -- Categories are named colours a message can carry several of. The colour is a token
        -- name rather than a value, so a category stays legible when the theme changes — a
        -- category holding #FF0000 would be invisible on the Black theme with nothing to do
        -- about it.
        CREATE TABLE categories (
            id            INTEGER PRIMARY KEY,
            name          TEXT    NOT NULL UNIQUE,
            colour_token  TEXT    NOT NULL,
            shortcut      TEXT,
            ordinal       INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE message_categories (
            message_id    INTEGER NOT NULL REFERENCES messages(id)   ON DELETE CASCADE,
            category_id   INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
            PRIMARY KEY (message_id, category_id)
        );

        CREATE INDEX categories_by_message ON message_categories (message_id);

        -- The reference's own six, by the names people already know them by.
        INSERT INTO categories (name, colour_token, ordinal) VALUES
            ('Red Category',    'category.red',    0),
            ('Orange Category', 'category.orange', 1),
            ('Yellow Category', 'category.yellow', 2),
            ('Green Category',  'category.green',  3),
            ('Blue Category',   'category.blue',   4),
            ('Purple Category', 'category.purple', 5);
