-- mail schema step 7, as introduced at c7dd2e65 on 2026-08-14
-- Render mail in a web engine, and say what was held back
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE safe_senders (
            address    TEXT    NOT NULL PRIMARY KEY,
            added_utc  INTEGER NOT NULL
        );
