-- mail schema step 8, as introduced at 07e97988 on 2026-08-15
-- Check a signature here, rather than believing a header about it
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE message_authentication (
            message_id      INTEGER NOT NULL PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
            -- The verdict as AuthVerdict spells it: none, pass, fail, softfail, neutral, error.
            dkim            TEXT    NOT NULL,
            -- The d= tag of the signature that passed, which is who the pass is evidence about.
            signing_domain  TEXT,
            checked_utc     INTEGER NOT NULL
        );
