-- mail schema step 9, as introduced at bb2ad917 on 2026-08-15
-- The Auto-Complete List: names offered under the To line as they are typed
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE nickname_cache (
            address        TEXT    NOT NULL PRIMARY KEY,
            display_name   TEXT    NOT NULL DEFAULT '',
            weight         INTEGER NOT NULL DEFAULT 0,
            last_used_utc  INTEGER NOT NULL
        );
