-- mail schema step 10, as introduced at b9f04239 on 2026-08-15
-- Phase 7: IMAP sync, with the store as the source of truth
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE folders ADD COLUMN imap_path     TEXT;
        ALTER TABLE folders ADD COLUMN uidvalidity   INTEGER;
        ALTER TABLE folders ADD COLUMN uidnext       INTEGER;
        ALTER TABLE folders ADD COLUMN highestmodseq INTEGER;
        -- 0 for a server folder that is listed but never pulled: a mailbox's own "everything"
        -- view holds a second copy of every message and would double the store.
        ALTER TABLE folders ADD COLUMN synced        INTEGER NOT NULL DEFAULT 1;

        CREATE TABLE sync_ops (
            id                INTEGER PRIMARY KEY,
            kind              TEXT    NOT NULL CHECK (kind IN ('flags', 'move', 'delete', 'append')),
            -- The folder the message is in on the server when the op is played.
            folder_id         INTEGER NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
            server_uid        TEXT,
            -- The local row, for writing a new UID back after a move or an append. Null once
            -- the row is gone, which a delete op does not mind.
            message_id        INTEGER          REFERENCES messages(id) ON DELETE SET NULL,
            target_folder_id  INTEGER          REFERENCES folders(id)  ON DELETE CASCADE,
            flag              TEXT    CHECK (flag IN ('seen', 'flagged')),
            value             INTEGER,
            created_utc       INTEGER NOT NULL,
            attempts          INTEGER NOT NULL DEFAULT 0,
            last_error        TEXT
        );

        CREATE INDEX sync_ops_by_folder ON sync_ops (folder_id, server_uid);
        CREATE INDEX sync_ops_by_message ON sync_ops (message_id);
