-- mail schema step 11, as introduced at 84e234e4 on 2026-08-15
-- Index the message body, so search reaches it
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN body_text TEXT NOT NULL DEFAULT '';

        DROP TRIGGER messages_fts_insert;
        DROP TRIGGER messages_fts_delete;
        DROP TRIGGER messages_fts_update;

        CREATE TRIGGER messages_fts_insert AFTER INSERT ON messages BEGIN
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, new.body_text);
        END;

        CREATE TRIGGER messages_fts_delete AFTER DELETE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, old.body_text);
        END;

        CREATE TRIGGER messages_fts_update AFTER UPDATE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, old.body_text);
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, new.body_text);
        END;
