-- mail schema step 12, as introduced at b644a42d on 2026-08-15
-- A Bayesian junk filter, trained on the reader's own mail
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE junk_tokens (
            token       TEXT    NOT NULL PRIMARY KEY,
            spam_count  INTEGER NOT NULL DEFAULT 0,
            ham_count   INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE junk_corpus (
            id             INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
            spam_messages  INTEGER NOT NULL DEFAULT 0,
            ham_messages   INTEGER NOT NULL DEFAULT 0
        );

        INSERT INTO junk_corpus (id, spam_messages, ham_messages) VALUES (1, 0, 0);

        CREATE TABLE blocked_senders (
            address    TEXT    NOT NULL PRIMARY KEY,
            added_utc  INTEGER NOT NULL
        );
