-- mail schema step 13, as introduced at 028d243b on 2026-08-15
-- Follow-up flags with a due date and the flag menu
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN follow_up_due      INTEGER;
        ALTER TABLE messages ADD COLUMN follow_up_complete INTEGER NOT NULL DEFAULT 0;

        CREATE INDEX messages_by_followup ON messages (follow_up_due)
            WHERE follow_up_due IS NOT NULL;
