-- mail schema step 14, as introduced at ebe30c8d on 2026-08-15
-- The Junk menu, Junk Email Options, and a seen list for POP3
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE pop3_seen (
            uidl            TEXT    NOT NULL PRIMARY KEY,
            first_seen_utc  INTEGER NOT NULL
        );

        INSERT OR IGNORE INTO pop3_seen (uidl, first_seen_utc)
        SELECT m.server_uid, m.received_utc
        FROM messages m JOIN folders f ON f.id = m.folder_id
        WHERE m.server_uid IS NOT NULL AND f.imap_path IS NULL
          AND (SELECT protocol FROM accounts ORDER BY id LIMIT 1) = 'pop3';
