-- mail schema step 15, as introduced at ebe30c8d on 2026-08-15
-- The Junk menu, Junk Email Options, and a seen list for POP3
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE safe_recipients (
            address    TEXT    NOT NULL PRIMARY KEY,
            added_utc  INTEGER NOT NULL
        );

        CREATE TABLE blocked_tlds (
            tld        TEXT    NOT NULL PRIMARY KEY,
            added_utc  INTEGER NOT NULL
        );

        CREATE TABLE blocked_encodings (
            charset    TEXT    NOT NULL PRIMARY KEY,
            added_utc  INTEGER NOT NULL
        );
