-- mail schema step 16, as introduced at 7a0f8d4d on 2026-08-15
-- Snooze: a message leaves the list and comes back at the set time
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN snooze_until INTEGER;

        CREATE INDEX messages_by_snooze ON messages (snooze_until)
            WHERE snooze_until IS NOT NULL;
