-- mail schema step 17, as introduced at 772caaf1 on 2026-08-15
-- Rules and Alerts: the engine, the wizard, and the rules that run on arrival
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE rules (
            id            INTEGER PRIMARY KEY,
            name          TEXT    NOT NULL,
            enabled       INTEGER NOT NULL DEFAULT 1,
            ordinal       INTEGER NOT NULL DEFAULT 0,
            definition    TEXT    NOT NULL,
            created_utc   INTEGER NOT NULL
        );
