-- mail schema step 18, as introduced at 2c9319d4 on 2026-08-15
-- Recover Deleted Items: a holding area for what was deleted for good
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE recoverable (
            id                    INTEGER PRIMARY KEY,
            blob_id               INTEGER NOT NULL REFERENCES blobs(id),
            original_folder_id    INTEGER,
            original_folder_name  TEXT    NOT NULL DEFAULT '',
            message_id            TEXT,
            from_name             TEXT    NOT NULL DEFAULT '',
            from_address          TEXT    NOT NULL DEFAULT '',
            subject               TEXT    NOT NULL DEFAULT '',
            preview               TEXT    NOT NULL DEFAULT '',
            body_text             TEXT    NOT NULL DEFAULT '',
            sent_utc              INTEGER,
            received_utc          INTEGER NOT NULL,
            size_bytes            INTEGER NOT NULL DEFAULT 0,
            is_read               INTEGER NOT NULL DEFAULT 0,
            is_flagged            INTEGER NOT NULL DEFAULT 0,
            has_attachment        INTEGER NOT NULL DEFAULT 0,
            deleted_utc           INTEGER NOT NULL
        );

        CREATE INDEX recoverable_by_deleted ON recoverable (deleted_utc);
