-- mail schema step 19, as introduced at 210e4166 on 2026-08-15
-- Search Folders: saved searches under each account in the folder pane
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN importance   INTEGER NOT NULL DEFAULT 1;
        ALTER TABLE messages ADD COLUMN to_addresses TEXT    NOT NULL DEFAULT '';
        ALTER TABLE messages ADD COLUMN cc_addresses TEXT    NOT NULL DEFAULT '';

        CREATE TABLE search_folders (
            id            INTEGER PRIMARY KEY,
            name          TEXT    NOT NULL,
            ordinal       INTEGER NOT NULL DEFAULT 0,
            definition    TEXT    NOT NULL,
            created_utc   INTEGER NOT NULL
        );
