-- mail schema step 20, as introduced at b4fda195 on 2026-08-15
-- Reminders on follow-up flags, and the Custom flag dialog
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN follow_up_type  TEXT;
        ALTER TABLE messages ADD COLUMN follow_up_start INTEGER;
        ALTER TABLE messages ADD COLUMN reminder_utc    INTEGER;

        CREATE INDEX messages_by_reminder ON messages (reminder_utc)
            WHERE reminder_utc IS NOT NULL;
