-- mail schema step 21, as introduced at ad795f78 on 2026-08-15
-- Focused Inbox: Focused and Other, sorted locally as mail arrives
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN is_focused INTEGER NOT NULL DEFAULT 1;

        CREATE TABLE focus_overrides (
            address    TEXT    NOT NULL PRIMARY KEY,
            focused    INTEGER NOT NULL,
            added_utc  INTEGER NOT NULL
        );
