-- mail schema step 22, as introduced at 8b41b012 on 2026-08-15
-- Ignore Conversation and Clean Up
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE ignored_conversations (
            thread_key  TEXT    NOT NULL PRIMARY KEY,
            subject     TEXT    NOT NULL DEFAULT '',
            added_utc   INTEGER NOT NULL
        );
