-- mail schema step 23, as introduced at a3dbc940 on 2026-08-15
-- Server-side rules over ManageSieve
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE rules ADD COLUMN server_side INTEGER NOT NULL DEFAULT 0;
        CREATE TABLE sieve_state (
            id             INTEGER PRIMARY KEY CHECK (id = 1),
            script         TEXT    NOT NULL,
            include        TEXT,
            published_utc  INTEGER NOT NULL,
            stale          INTEGER NOT NULL DEFAULT 0
        );
