-- mail schema step 24, as introduced at 9da17bde on 2026-08-15
-- Change View and Advanced View Settings
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE folders ADD COLUMN view_json TEXT;
        CREATE TABLE views (
            id            INTEGER PRIMARY KEY,
            name          TEXT    NOT NULL UNIQUE COLLATE NOCASE,
            definition    TEXT    NOT NULL,
            created_utc   INTEGER NOT NULL
        );
