-- mail schema step 25, as introduced at a852c20a on 2026-08-15
-- AutoArchive, and Mailbox Cleanup's other actions
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN expires_utc INTEGER;
        ALTER TABLE folders ADD COLUMN autoarchive_json TEXT;
