-- mail schema step 26, as introduced at 5eb4b3db on 2026-08-26
-- The Folder tab, the View tab, and the Server group the Send/Receive tab was missing
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN header_only INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE messages ADD COLUMN marked_download INTEGER NOT NULL DEFAULT 0;
