-- mail schema step 27, as introduced at e3bea03f on 2026-08-27
-- The reader now asks politely, and remembers what it was told
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN feed_link  TEXT;
        ALTER TABLE messages ADD COLUMN feed_image TEXT;
