-- mail schema step 28, as introduced at 0c406a42 on 2026-08-27
-- Boards, and the feeds that publish a sentence and a link
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE TABLE boards (
            id            INTEGER PRIMARY KEY,
            name          TEXT    NOT NULL UNIQUE COLLATE NOCASE,
            description   TEXT    NOT NULL DEFAULT '',
            ordinal       INTEGER NOT NULL DEFAULT 0,
            created_utc   INTEGER NOT NULL
        );

        CREATE TABLE board_items (
            board_id      INTEGER NOT NULL REFERENCES boards(id)   ON DELETE CASCADE,
            message_id    INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            saved_utc     INTEGER NOT NULL,
            PRIMARY KEY (board_id, message_id)
        );

        CREATE INDEX board_items_by_message ON board_items (message_id);
