-- mail schema step 29, as introduced at 7567c996 on 2026-08-27
-- The line under the headline says which paper it is
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN feed_words INTEGER;
