-- mail schema step 30, as introduced at daea6cb0 on 2026-08-29
-- The search index could never be rebuilt
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        DROP TRIGGER messages_fts_insert;
        DROP TRIGGER messages_fts_delete;
        DROP TRIGGER messages_fts_update;
        DROP TABLE messages_fts;

        CREATE VIRTUAL TABLE messages_fts USING fts5 (
            subject,
            from_name,
            from_address,
            preview,
            body_text,
            content = 'messages',
            content_rowid = 'id',
            tokenize = 'unicode61 remove_diacritics 2'
        );

        INSERT INTO messages_fts (messages_fts) VALUES ('rebuild');

        CREATE TRIGGER messages_fts_insert AFTER INSERT ON messages BEGIN
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body_text)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, new.body_text);
        END;

        CREATE TRIGGER messages_fts_delete AFTER DELETE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body_text)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, old.body_text);
        END;

        CREATE TRIGGER messages_fts_update AFTER UPDATE ON messages BEGIN
            INSERT INTO messages_fts (messages_fts, rowid, subject, from_name, from_address,
                                      preview, body_text)
            VALUES ('delete', old.id, old.subject, old.from_name, old.from_address,
                    old.preview, old.body_text);
            INSERT INTO messages_fts (rowid, subject, from_name, from_address, preview, body_text)
            VALUES (new.id, new.subject, new.from_name, new.from_address, new.preview, new.body_text);
        END;
