-- mail schema step 31, as introduced at 24751615 on 2026-08-29
-- One name per shelf, the top level included, and no separators in a name
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        UPDATE folders SET name = name || ' (' || id || ')'
        WHERE parent_id IS NULL
          AND EXISTS (SELECT 1 FROM folders earlier
                      WHERE earlier.account_id = folders.account_id
                        AND earlier.parent_id IS NULL
                        AND earlier.name = folders.name
                        AND earlier.id < folders.id);

        CREATE UNIQUE INDEX folders_top_level_name
            ON folders (account_id, name) WHERE parent_id IS NULL;
