-- mail schema step 32, as introduced at 2bcc376a on 2026-08-29
-- A conversation is a reply relationship
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        CREATE INDEX messages_by_in_reply_to ON messages (in_reply_to)
            WHERE in_reply_to IS NOT NULL;
