-- mail schema step 33, as introduced at bf5c3a28 on 2026-08-29
-- The Backstage leaves the close button alone, and By Type learns what a row is
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN item_type TEXT;
