-- mail schema step 34, as introduced at 0204473d on 2026-08-30
-- The mail the window left behind is reachable: paging, fetch-older, and a search that asks the server
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE folders ADD COLUMN server_older INTEGER NOT NULL DEFAULT 0;
