-- mail schema step 35, as introduced at 6a1e37de on 2026-08-30
-- The Icon column tells replied and forwarded from merely read
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN answered INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE messages ADD COLUMN forwarded INTEGER NOT NULL DEFAULT 0;

        CREATE TABLE sync_ops_new (
            id                INTEGER PRIMARY KEY,
            kind              TEXT    NOT NULL CHECK (kind IN ('flags', 'move', 'delete', 'append')),
            folder_id         INTEGER NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
            server_uid        TEXT,
            message_id        INTEGER          REFERENCES messages(id) ON DELETE SET NULL,
            target_folder_id  INTEGER          REFERENCES folders(id)  ON DELETE CASCADE,
            flag              TEXT    CHECK (flag IN ('seen', 'flagged', 'answered', 'forwarded')),
            value             INTEGER,
            created_utc       INTEGER NOT NULL,
            attempts          INTEGER NOT NULL DEFAULT 0,
            last_error        TEXT
        );

        INSERT INTO sync_ops_new SELECT * FROM sync_ops;
        DROP TABLE sync_ops;
        ALTER TABLE sync_ops_new RENAME TO sync_ops;

        CREATE INDEX sync_ops_by_folder ON sync_ops (folder_id, server_uid);
        CREATE INDEX sync_ops_by_message ON sync_ops (message_id);
