-- mail schema step 36, as introduced at 633751db on 2026-08-30
-- An arriving read-receipt request is answered, the way the radios say
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE messages ADD COLUMN receipt_settled INTEGER NOT NULL DEFAULT 0;
