-- mail schema step 37, as introduced at 32669eed on 2026-10-06
-- Show a message that wears several Gmail labels once when searching across folders.
-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step
-- is never changed, and this file is the record that it has not been.
        ALTER TABLE accounts ADD COLUMN labels INTEGER NOT NULL DEFAULT 0;
