#!/usr/bin/env bash
# The Phase 10 pixel gate (§8): the four built-in themes stay pixel-identical to their
# reference captures as the token system evolves.
#
# What one run does, per theme:
#   1. captures the shell twice, from two separate application runs over one seeded store —
#      the pair must be pixel-identical, which proves the capture is deterministic before any
#      reference is consulted;
#   2. compares the capture against tests/fidelity/<theme>.png when that reference exists.
#
# References are environment-specific (font rasterisation differs across machines), so they
# are generated by the same environment that checks them: run this on CI, download the
# fidelity artifact from a green run, and commit its PNGs as tests/fidelity/*.png. To refresh
# them in place on that same environment: tools/fidelity-gate.sh --update.
#
# Needs a display (CI wraps this with xvfb-run) and ImageMagick's `magick`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
refs="$root/tests/fidelity"
out="$root/artifacts/fidelity"
update=false
[[ "${1:-}" == "--update" ]] && update=true

# ImageMagick 7 fronts everything with `magick`; Ubuntu's ImageMagick 6 still ships the bare
# `compare`. Either will do.
if command -v magick >/dev/null; then
  compare_tool=(magick compare)
elif command -v compare >/dev/null; then
  compare_tool=(compare)
else
  echo "fidelity-gate: ImageMagick is required ('magick' or 'compare')." >&2
  exit 2
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$out"

echo "fidelity-gate: seeding a store pinned to the reference day"
MAILBOX_SEED="$work/seed" MAILBOX_TODAY=2026-08-16 \
  dotnet test "$root/tests/Mailbox.Tests" --filter SeedOnRequest -v quiet >"$work/seed.log" 2>&1 \
  || { echo "fidelity-gate: seeding failed"; cat "$work/seed.log"; exit 1; }

# Every Avalonia application on Linux can print an unhandled TaskCanceledException on the way
# out: Avalonia.FreeDesktop tears its own D-Bus connection down after the dispatcher has already
# stopped, so that connection's blocking Send onto the dispatcher is cancelled. It is upstream,
# it is cosmetic, and the process still exits 0 — which is why this check reads the log instead
# of the exit code, and equally why the trace has to be let back through it. It is a race, so it
# appears in some runs and not others: CI has no session bus under xvfb and has never printed
# one, but a local run has a bus, and failing a capture there for something the application did
# not do is a bad reason to distrust a picture.
#
# That one trace goes and nothing else does. A block qualifies only when it is a
# TaskCanceledException raised through Tmds.DBus — which nothing under src/ binds, so those
# frames can only be Avalonia's own — and names nothing of ours anywhere in it. Every other
# exception, and any trace at all carrying one of our frames, still fails the capture.
app_exceptions() { # log -> the lines naming an exception, that one trace excluded
  awk '
    /^Unhandled exception\./ { settle(); block = $0; held = 1; next }
    held && /^[[:space:]]/   { block = block "\n" $0; next }
                             { settle(); print }
    END                      { settle() }
    function settle(   upstream) {
      if (!held) return
      upstream = block ~ /TaskCanceledException/ &&
                 block ~ /Tmds\.DBus\.Protocol\.DBusConnection/ &&
                 block !~ /Mailbox\./
      if (!upstream) print block
      held = 0
    }
  ' "$1" | { grep -i exception || true; }
}

capture() { # theme, output
  MAILBOX_STORE="$work/seed/accounts" MAILBOX_TODAY=2026-08-16 MAILBOX_THEME="$1" \
    MAILBOX_STATE=no-reading MAILBOX_SIZE=1600x1000 MAILBOX_CAPTURE="$2" \
    dotnet run --project "$root/src/Mailbox.App" >"$work/$1.log" 2>&1 \
    || { echo "fidelity-gate: the $1 capture run failed"; tail -40 "$work/$1.log"; return 1; }
  # Declared apart from the assignment on purpose: `local x=$(...)` reports local's status, not
  # the command's, and a filter that broke would then read as a capture with nothing to report —
  # a check that passes because it stopped running, which is the failure this gate exists to
  # avoid making.
  local logged
  if ! logged="$(app_exceptions "$work/$1.log")"; then
    echo "fidelity-gate: the exception filter failed to read the $1 capture log"; return 1
  fi
  if [[ -n "$logged" ]]; then
    echo "fidelity-gate: the $1 capture logged an exception"; printf '%s\n' "$logged" | head -5; return 1
  fi
}

differing() { # a, b -> prints the AE count
  # compare exits 1 when the images differ — that is an answer, not a failure, and under
  # pipefail it must be absorbed here or the script dies before it can say what drifted.
  { "${compare_tool[@]}" -metric AE "$1" "$2" null: 2>&1 || true; } | cut -d' ' -f1
}

status=0
for theme in colorful white darkgray black; do
  echo "fidelity-gate: $theme"
  capture "$theme" "$out/$theme.png" || { status=1; continue; }
  capture "$theme" "$work/$theme-again.png" || { status=1; continue; }

  same_run=$(differing "$out/$theme.png" "$work/$theme-again.png")
  if [[ "$same_run" != "0" ]]; then
    echo "fidelity-gate: FAIL — two captures of $theme in one run differ by $same_run pixels: the capture is not deterministic."
    "${compare_tool[@]}" "$out/$theme.png" "$work/$theme-again.png" "$out/$theme-selfdiff.png" || true
    status=1
    continue
  fi

  if $update; then
    mkdir -p "$refs"
    cp "$out/$theme.png" "$refs/$theme.png"
    echo "fidelity-gate: reference updated: tests/fidelity/$theme.png"
  elif [[ -f "$refs/$theme.png" ]]; then
    drift=$(differing "$refs/$theme.png" "$out/$theme.png")
    if [[ "$drift" == "0" ]]; then
      echo "fidelity-gate: $theme is pixel-identical to its reference."
    else
      echo "fidelity-gate: FAIL — $theme differs from its reference by $drift pixels."
      "${compare_tool[@]}" "$refs/$theme.png" "$out/$theme.png" "$out/$theme-diff.png" || true
      status=1
    fi
  else
    echo "fidelity-gate: no reference for $theme yet — capture recorded at artifacts/fidelity/$theme.png."
  fi
done

exit $status
