#!/usr/bin/env bash
# The Phase 10 pixel gate (§8): the four built-in themes stay pixel-identical to their
# reference captures as the token system evolves.
#
# What one run does, per theme:
#   1. captures the shell twice, from two separate application runs over one seeded store —
#      the pair must be pixel-identical, which proves the capture is deterministic before any
#      reference is consulted;
#   2. compares the capture against tests/fidelity/<theme>.png when that reference exists.
#
# References are environment-specific (font rasterisation differs across machines), so they
# are generated by the same environment that checks them: run this on CI, download the
# fidelity artifact from a green run, and commit its PNGs as tests/fidelity/*.png. To refresh
# them in place on that same environment: tools/fidelity-gate.sh --update.
#
# Needs a display (CI wraps this with xvfb-run) and ImageMagick's `magick`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
refs="$root/tests/fidelity"
out="$root/artifacts/fidelity"
update=false
[[ "${1:-}" == "--update" ]] && update=true

# ImageMagick 7 fronts everything with `magick`; Ubuntu's ImageMagick 6 still ships the bare
# `compare`. Either will do.
if command -v magick >/dev/null; then
  compare_tool=(magick compare)
elif command -v compare >/dev/null; then
  compare_tool=(compare)
else
  echo "fidelity-gate: ImageMagick is required ('magick' or 'compare')." >&2
  exit 2
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$out"

echo "fidelity-gate: seeding a store pinned to the reference day"
MAILBOX_SEED="$work/seed" MAILBOX_TODAY=2026-08-16 \
  dotnet test "$root/tests/Mailbox.Tests" --filter SeedOnRequest -v quiet >"$work/seed.log" 2>&1 \
  || { echo "fidelity-gate: seeding failed"; cat "$work/seed.log"; exit 1; }

capture() { # theme, output
  MAILBOX_STORE="$work/seed/accounts" MAILBOX_TODAY=2026-08-16 MAILBOX_THEME="$1" \
    MAILBOX_STATE=no-reading MAILBOX_SIZE=1600x1000 MAILBOX_CAPTURE="$2" \
    dotnet run --project "$root/src/Mailbox.App" >"$work/$1.log" 2>&1 \
    || { echo "fidelity-gate: the $1 capture run failed"; tail -40 "$work/$1.log"; return 1; }
  if grep -qi exception "$work/$1.log"; then
    echo "fidelity-gate: the $1 capture logged an exception"; grep -i exception "$work/$1.log" | head -5; return 1
  fi
}

differing() { # a, b -> prints the AE count
  "${compare_tool[@]}" -metric AE "$1" "$2" null: 2>&1 | cut -d' ' -f1
}

status=0
for theme in colorful white darkgray black; do
  echo "fidelity-gate: $theme"
  capture "$theme" "$out/$theme.png" || { status=1; continue; }
  capture "$theme" "$work/$theme-again.png" || { status=1; continue; }

  same_run=$(differing "$out/$theme.png" "$work/$theme-again.png")
  if [[ "$same_run" != "0" ]]; then
    echo "fidelity-gate: FAIL — two captures of $theme in one run differ by $same_run pixels: the capture is not deterministic."
    "${compare_tool[@]}" "$out/$theme.png" "$work/$theme-again.png" "$out/$theme-selfdiff.png" || true
    status=1
    continue
  fi

  if $update; then
    mkdir -p "$refs"
    cp "$out/$theme.png" "$refs/$theme.png"
    echo "fidelity-gate: reference updated: tests/fidelity/$theme.png"
  elif [[ -f "$refs/$theme.png" ]]; then
    drift=$(differing "$refs/$theme.png" "$out/$theme.png")
    if [[ "$drift" == "0" ]]; then
      echo "fidelity-gate: $theme is pixel-identical to its reference."
    else
      echo "fidelity-gate: FAIL — $theme differs from its reference by $drift pixels."
      "${compare_tool[@]}" "$refs/$theme.png" "$out/$theme.png" "$out/$theme-diff.png" || true
      status=1
    fi
  else
    echo "fidelity-gate: no reference for $theme yet — capture recorded at artifacts/fidelity/$theme.png."
  fi
done

exit $status
