#!/usr/bin/env python3
"""Generate IconGlyphs.cs from the Fluent UI System Icons metadata.

The bundled font is microsoft/fluentui-system-icons (MIT). This script maps Mailbox's
logical icon names onto its codepoints so that commands can reference icons by name and a
theme can swap the entire icon set without touching a command definition.

Usage:
    curl -fsSLO https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/fonts/FluentSystemIcons-Regular.json
    python3 tools/generate-icons.py FluentSystemIcons-Regular.json
"""

import json
import pathlib
import sys

# Logical name -> Fluent base name. Add here, then regenerate.
WANTED = {
    "mail-new": "mail_add",
    "new-items": "document_add",
    "delete": "delete",
    "archive": "archive",
    "ignore": "dismiss_circle",
    "cleanup": "broom",
    "junk": "prohibited",
    "reply": "arrow_reply",
    "reply-all": "arrow_reply_all",
    "forward": "arrow_forward",
    "meeting": "calendar_ltr",
    "move": "folder_arrow_right",
    "rules": "flash",
    "quicksteps": "flash_sparkle",
    "unread": "mail_unread",
    "categorize": "tag",
    "flag": "flag",
    "search": "search",
    "address-book": "book_contacts",
    "filter": "filter",
    "send-receive": "arrow_sync",
    "work-offline": "plug_disconnected",
    "snooze": "clock",
    "source": "code",
    "tracker": "eye_off",
    "shield": "shield",
    "chevron-down": "chevron_down",
    "chevron-right": "chevron_right",
    "mail": "mail",
    "calendar": "calendar_ltr",
    "people": "people",
    "person-add": "person_add",
    "tasks": "task_list_square_ltr",
    "notes": "note",
    "journal": "book",
    "attach": "attach",
    "print": "print",
    "settings": "settings",
    "more": "more_horizontal",
    "undo": "arrow_undo",
    "pin": "pin",
    "folder": "folder",
    "folder-open": "folder_open",
    "star": "star",
    "warning": "warning",
    "info": "info",
    "dismiss": "dismiss",
    "redo": "arrow_redo",
    "send": "send",
    "update-folder": "folder_sync",
    "sr-groups": "folder_multiple",
    "show-progress": "arrow_sync_circle",
    "cancel": "dismiss_circle",
    "apps": "grid",
    "change-view": "arrow_swap",
    "view-settings": "settings_cog_multiple",
    "arrange": "arrow_sort",
    "reverse-sort": "arrow_sort_up",
    "spacing": "arrow_autofit_height",
    "layout": "panel_left",
    "reader": "reading_mode_mobile",
    "read-aloud": "sound_source",
    "avatar": "person_circle",
    "collapse-left": "chevron_left",
    "chevron-left": "chevron_left",
    "chevron-up": "chevron_up",
    "expand-right": "chevron_right",
    "dock": "open",
    "zoom-in": "add",
    "zoom-out": "subtract",
    "reading-pane": "panel_right",
    "message-preview": "panel_bottom",
    "importance": "important",
    "reminder": "alert",
    "mark-complete": "checkmark_circle",
    "new-task": "task_list_add",
    "share": "share",
    "private": "lock_closed",
    "focus-time": "lightbulb",
    "today": "calendar_today",
    "next-7": "calendar_week_numbers",
    "day-view": "calendar_day",
    "work-week": "calendar_work_week",
    "week-view": "calendar_week_start",
    "month-view": "calendar_month",
    "schedule-view": "calendar_agenda",
    "add": "add",
}

SIZES = (16, 20, 24, 32)

HEADER = '''// <auto-generated>
//   Generated from the Fluent UI System Icons metadata (MIT, microsoft/fluentui-system-icons).
//   Regenerate with tools/generate-icons.py rather than editing by hand.
// </auto-generated>

namespace Mailbox.Theming.Icons;

/// <summary>
/// Maps Mailbox's logical icon names onto glyphs in the bundled Fluent UI System Icons font.
/// </summary>
/// <remarks>
/// Commands reference icons by logical name, never by codepoint, so a theme can swap the whole
/// icon set without touching a single command definition.
/// <para>
/// Fluent ships separately drawn artwork per size rather than one outline scaled up — a 16px
/// glyph carries less detail than its 24px sibling by design. Asking for the size you will
/// actually render at is what keeps icons crisp.
/// </para>
/// </remarks>
public static class IconGlyphs
{
    /// <summary>Sizes the bundled font provides artwork for.</summary>
    public static readonly int[] Sizes = [16, 20, 24, 32];

    // Values are strings rather than chars: Fluent places some glyphs in supplementary
    // private-use planes above U+FFFF, which do not fit in a 16-bit char and need a
    // surrogate pair.
    private static readonly Dictionary<string, Dictionary<int, string>> Map =
        new(StringComparer.OrdinalIgnoreCase)
    {
'''

FOOTER = '''    };

    public static IReadOnlyCollection<string> Names => Map.Keys;

    public static bool Has(string name) => Map.ContainsKey(name);

    /// <summary>
    /// The glyph for a logical name at the nearest available size, rounding down so a request
    /// never returns artwork drawn with more detail than the target can show.
    /// </summary>
    public static string Get(string name, int size = 20)
    {
        if (!Map.TryGetValue(name, out var bySize))
        {
            throw new KeyNotFoundException(
                $"No icon named '{name}'. Add it to tools/generate-icons.py and regenerate.");
        }

        if (bySize.TryGetValue(size, out var exact)) return exact;

        var best = bySize.Keys.Where(s => s <= size).DefaultIfEmpty(bySize.Keys.Min()).Max();
        return bySize[best];
    }

    /// <summary>Never throws. Returns an empty string for an unknown name.</summary>
    public static string GetOrEmpty(string name, int size = 20)
        => Map.ContainsKey(name) ? Get(name, size) : string.Empty;
}
'''


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2

    metadata = json.loads(pathlib.Path(sys.argv[1]).read_text())

    resolved: dict[str, dict[int, int]] = {}
    missing: list[str] = []

    for logical, base in sorted(WANTED.items()):
        found = {
            size: metadata[key]
            for size in SIZES
            if (key := f"ic_fluent_{base}_{size}_regular") in metadata
        }
        if found:
            resolved[logical] = found
        else:
            missing.append(f"{logical} -> {base}")

    if missing:
        print("Unresolved icon names:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        return 1

    def escape(cp: int) -> str:
        # \uXXXX only covers the BMP; anything above needs the 8-digit \UXXXXXXXX form.
        return f'"\\u{cp:04X}"' if cp <= 0xFFFF else f'"\\U{cp:08X}"'

    body = "".join(
        "        [\"{}\"] = new() {{ {} }},\n".format(
            name,
            ", ".join(f"[{s}] = {escape(cp)}" for s, cp in sorted(sizes.items())),
        )
        for name, sizes in sorted(resolved.items())
    )

    out = pathlib.Path(__file__).parent.parent / "src/Mailbox.Theming/Icons/IconGlyphs.cs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEADER + body + FOOTER)

    codepoints = {cp for sizes in resolved.values() for cp in sizes.values()}
    print(f"Wrote {out} — {len(resolved)} icons, {len(codepoints)} glyphs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
