#!/usr/bin/env python3
"""Writes the historical schema fixtures under tests/fixtures/schema/, from git history.

Both stores' schemas are ordered lists of steps that are only ever appended to
(Mailbox.Store.Schema.Migrations, Mailbox.Store.Pim.PimMigrations). A store at historical
version N is therefore the first N steps run in order — but only if no shipped step has ever
been edited since, and *that* is the claim this script checks rather than assumes.

So it walks the git history of each migrations file, takes each step's text from the commit
that first introduced it, and writes it out as one .sql file per step:

    tests/fixtures/schema/mail/01.sql .. 29.sql
    tests/fixtures/schema/pim/01.sql  ..  8.sql

Each file carries the commit that introduced it in a header comment. A store at version N is
made by running 01..N and stamping `PRAGMA user_version = N`, which is exactly what
SqliteStore.Migrate does; AuditStoreMigrationTests does it that way and migrates the result
with the real MailStore/PimStore.

Keeping the steps as they were *in history* rather than as the tree has them today is the
point: if a shipped step is ever edited, the fixture and the tree part company and the
regeneration below prints the step that moved. Every store already migrated past an edited
step would otherwise differ from a fresh one with nothing able to tell which is which.

    tools/make-schema-fixtures.py           # regenerate; prints what changed, if anything
    tools/make-schema-fixtures.py --check   # exit 1 if anything would change
"""

import argparse
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "tests", "fixtures", "schema")

SOURCES = [
    ("mail", "src/Mailbox.Store/Schema/Migrations.cs"),
    ("pim", "src/Mailbox.Store/Pim/PimMigrations.cs"),
]


def git(*args):
    done = subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True)
    if done.returncode != 0:
        raise SystemExit(f"git {' '.join(args)}: {done.stderr.strip()}")
    return done.stdout


def steps_of(text):
    """The raw-string literals of a migrations file, in order."""
    return re.findall(r'"""\n(.*?)\n\s*"""', text, re.S)


def history(path):
    """(sha, date, subject, path-at-that-commit) oldest first, for commits touching the file."""
    raw = git("log", "--follow", "--format=%H|%ad|%s", "--date=short", "--name-only", "--", path)
    out, pending = [], None
    for line in raw.splitlines():
        head = line.split("|")
        if len(head) >= 3 and len(head[0]) == 40 and all(c in "0123456789abcdef" for c in head[0]):
            pending = head
        elif line.strip() and pending:
            out.append((pending[0], pending[1], "|".join(pending[2:]), line.strip()))
            pending = None
    return list(reversed(out))


def introductions(path):
    """For each step index, the commit that first carried it, and its text at that commit."""
    first = {}
    for sha, date, subject, at in history(path):
        for index, step in enumerate(steps_of(git("show", f"{sha}:{at}")), start=1):
            first.setdefault(index, (sha, date, subject, step))
    return first


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if stale")
    options = parser.parse_args()

    stale = False
    for name, path in SOURCES:
        current = steps_of(open(os.path.join(REPO, path), encoding="utf-8").read())
        first = introductions(path)

        if len(first) != len(current):
            print(f"{name}: history carries {len(first)} steps, the tree carries {len(current)}")
            stale = True

        edited = [i for i, (_, _, _, text) in first.items()
                  if i <= len(current) and text.strip() != current[i - 1].strip()]
        if edited:
            print(f"{name}: shipped steps EDITED since they were introduced: {edited}")
            print("       a store migrated past one of these differs from a fresh store, "
                  "and nothing in the file can say which it is.")
            stale = True

        folder = os.path.join(OUT, name)
        os.makedirs(folder, exist_ok=True)
        for index in sorted(first):
            sha, date, subject, text = first[index]
            body = (f"-- {name} schema step {index}, as introduced at {sha[:8]} on {date}\n"
                    f"-- {subject}\n"
                    f"-- Generated by tools/make-schema-fixtures.py. Do not edit: a shipped step\n"
                    f"-- is never changed, and this file is the record that it has not been.\n"
                    f"{text}\n")
            file = os.path.join(folder, f"{index:02d}.sql")
            was = open(file, encoding="utf-8").read() if os.path.exists(file) else None
            if was != body:
                stale = True
                print(f"{'stale' if options.check else 'wrote'} {os.path.relpath(file, REPO)}")
                if not options.check:
                    open(file, "w", encoding="utf-8").write(body)

        print(f"{name}: {len(first)} step(s) under {os.path.relpath(folder, REPO)}")

    if options.check and stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
