// <auto-generated>
//   Generated from the Fluent UI System Icons metadata (MIT, microsoft/fluentui-system-icons).
//   Regenerate with tools/generate-icons.py rather than editing by hand.
// </auto-generated>

namespace Mailbox.Theming.Icons;

/// <summary>
/// Maps Mailbox's logical icon names onto glyphs in the bundled Fluent UI System Icons font.
/// </summary>
/// <remarks>
/// Commands reference icons by logical name, never by codepoint, so a theme can swap the whole
/// icon set without touching a single command definition.
/// <para>
/// Fluent ships separately drawn artwork per size rather than one outline scaled up — a 16px
/// glyph carries less detail than its 24px sibling by design. Asking for the size you will
/// actually render at is what keeps icons crisp.
/// </para>
/// </remarks>
public static class IconGlyphs
{
    /// <summary>Sizes the bundled font provides artwork for.</summary>
    public static readonly int[] Sizes = [16, 20, 24, 32];

    // Values are strings rather than chars: Fluent places some glyphs in supplementary
    // private-use planes above U+FFFF, which do not fit in a 16-bit char and need a
    // surrogate pair.
    private static readonly Dictionary<string, Dictionary<int, string>> Map =
        new(StringComparer.OrdinalIgnoreCase)
    {
        ["3d-models"] = new() { [16] = "\uF334", [20] = "\uF335", [24] = "\uF336", [32] = "\uEECA" },
        ["accessibility"] = new() { [20] = "\uE003", [24] = "\uE004", [32] = "\uF00B" },
        ["add"] = new() { [16] = "\uF108", [20] = "\uF109", [24] = "\uF10A", [32] = "\uF58D" },
        ["address-book"] = new() { [16] = "\U000F09AD", [20] = "\uE16A", [24] = "\uE16B", [32] = "\uE16D" },
        ["align"] = new() { [16] = "\uECC3", [20] = "\uF79F", [24] = "\uF7A0" },
        ["apps"] = new() { [16] = "\uE6C3", [20] = "\uF462", [24] = "\uF463" },
        ["archive"] = new() { [16] = "\uF8CC", [20] = "\uF139", [24] = "\uF13A", [32] = "\uE066" },
        ["arrange"] = new() { [16] = "\uF1AB", [20] = "\uF18A", [24] = "\uF18B" },
        ["attach"] = new() { [16] = "\uF1A8", [20] = "\uF1A9", [24] = "\uF1AA", [32] = "\U000F0427" },
        ["avatar"] = new() { [16] = "\U000F0B55", [20] = "\uE928", [24] = "\uE929", [32] = "\uF042" },
        ["bcc"] = new() { [20] = "\uF511", [24] = "\uF512", [32] = "\U000F05D9" },
        ["bold"] = new() { [16] = "\uECD2", [20] = "\uF7A4", [24] = "\uF7A5" },
        ["bullets"] = new() { [16] = "\U000F028F", [20] = "\U000F0290", [24] = "\U000F0291" },
        ["calendar"] = new() { [16] = "\uE24D", [20] = "\uE24E", [24] = "\uE24F", [32] = "\uE251" },
        ["cancel"] = new() { [16] = "\uF36C", [20] = "\uF36D", [24] = "\uF36E", [32] = "\uE4C3" },
        ["categorize"] = new() { [16] = "\uEC70", [20] = "\uF77C", [24] = "\uF77D", [32] = "\uEC72" },
        ["change-styles"] = new() { [16] = "\U000F03A3", [20] = "\uF7D9", [24] = "\uF7DA" },
        ["change-view"] = new() { [16] = "\U000F02A4", [20] = "\uF18D", [24] = "\uF18E" },
        ["chart"] = new() { [16] = "\U000F05D4", [20] = "\uE2DD", [24] = "\uE2DE", [32] = "\U000F0816" },
        ["check-names"] = new() { [16] = "\uF5C9", [20] = "\uE924", [24] = "\uF5CA" },
        ["chevron-down"] = new() { [16] = "\uF2A2", [20] = "\uF2A3", [24] = "\uF2A4", [32] = "\U000F0320" },
        ["chevron-left"] = new() { [16] = "\uF2A9", [20] = "\uF2AA", [24] = "\uF2AB", [32] = "\U000F0321" },
        ["chevron-right"] = new() { [16] = "\uF2AF", [20] = "\uF2B0", [24] = "\uF2B1", [32] = "\U000F0322" },
        ["chevron-up"] = new() { [16] = "\uF2B5", [20] = "\uF2B6", [24] = "\uF2B7", [32] = "\U000F0323" },
        ["cleanup"] = new() { [16] = "\uF1FE", [20] = "\uF201", [24] = "\uF202", [32] = "\U000F0429" },
        ["clear-formatting"] = new() { [16] = "\uECF3", [20] = "\uF7BC", [24] = "\uF7BD", [32] = "\U000F0BD3" },
        ["collapse-left"] = new() { [16] = "\uF2A9", [20] = "\uF2AA", [24] = "\uF2AB", [32] = "\U000F0321" },
        ["contact-card"] = new() { [16] = "\uF362", [20] = "\uF31F", [24] = "\uF320", [32] = "\uE40A" },
        ["copy"] = new() { [16] = "\uF32A", [20] = "\uF32B", [24] = "\uF32C", [32] = "\U000F0006" },
        ["cut"] = new() { [16] = "\U000F038C", [20] = "\uF33A", [24] = "\uF33B", [32] = "\U000F09B8" },
        ["day-view"] = new() { [16] = "\uE244", [20] = "\uF222", [24] = "\uF223", [32] = "\U000F09D5" },
        ["delay-delivery"] = new() { [16] = "\uE36F", [20] = "\uF2E1", [24] = "\uF2E2", [32] = "\uE370" },
        ["delete"] = new() { [16] = "\uE47B", [20] = "\uF34C", [24] = "\uF34D", [32] = "\uEEA6" },
        ["dictate"] = new() { [16] = "\uE7F8", [20] = "\uE7F9", [24] = "\uE7FA", [32] = "\uE7FC" },
        ["direct-replies"] = new() { [16] = "\uF17A", [20] = "\uF17B", [24] = "\uF17C", [32] = "\U000F0426" },
        ["dismiss"] = new() { [16] = "\uF368", [20] = "\uF369", [24] = "\uF36A", [32] = "\uF3F3" },
        ["dock"] = new() { [16] = "\uF581", [20] = "\uF582", [24] = "\uF583", [32] = "\uF667" },
        ["editor"] = new() { [20] = "\uED15", [24] = "\uED16" },
        ["encrypt"] = new() { [16] = "\U000F0407", [20] = "\uF502", [24] = "\uF503", [32] = "\U000F0409" },
        ["equation"] = new() { [16] = "\uE7E1", [20] = "\uE7E2", [24] = "\uE7E3", [32] = "\uE7E4" },
        ["expand-right"] = new() { [16] = "\uF2AF", [20] = "\uF2B0", [24] = "\uF2B1", [32] = "\U000F0322" },
        ["filter"] = new() { [16] = "\uE60A", [20] = "\uF406", [24] = "\uF407", [32] = "\U000F0432" },
        ["flag"] = new() { [16] = "\uF40A", [20] = "\uF40B", [24] = "\uF40C", [32] = "\U000F003C" },
        ["focus-time"] = new() { [16] = "\uF4D5", [20] = "\uF4D6", [24] = "\uF4D7", [32] = "\uF07D" },
        ["folder"] = new() { [16] = "\uE643", [20] = "\uF418", [24] = "\uF419", [32] = "\uE644" },
        ["folder-open"] = new() { [16] = "\uF42D", [20] = "\uF42E", [24] = "\uF42F" },
        ["font"] = new() { [16] = "\uF7E3", [20] = "\uF7E4", [24] = "\uF7E5" },
        ["font-color"] = new() { [16] = "\uECF5", [20] = "\uF7BF", [24] = "\uF7C0" },
        ["font-size"] = new() { [16] = "\uED10", [20] = "\uF7E6", [24] = "\uF7E7" },
        ["format-painter"] = new() { [16] = "\uF591", [20] = "\uF592", [24] = "\uF593", [32] = "\U000F0224" },
        ["forward"] = new() { [16] = "\uF156", [20] = "\uF157", [24] = "\uF158", [32] = "\U000F0424" },
        ["from-field"] = new() { [16] = "\uE937", [20] = "\uE938", [24] = "\uE939", [32] = "\U000F066A" },
        ["grow-font"] = new() { [20] = "\uF439", [24] = "\uF43A" },
        ["highlight"] = new() { [16] = "\uF47B", [20] = "\uF47C", [24] = "\uF47D" },
        ["icons"] = new() { [16] = "\uF3DF", [20] = "\uF3E0", [24] = "\uF3E1", [32] = "\uE5C5" },
        ["ignore"] = new() { [16] = "\uF36C", [20] = "\uF36D", [24] = "\uF36E", [32] = "\uE4C3" },
        ["immersive"] = new() { [20] = "\uF65B", [24] = "\uF65C" },
        ["importance"] = new() { [16] = "\uF49E", [20] = "\uF49F", [24] = "\uF4A0", [32] = "\U000F0444" },
        ["importance-low"] = new() { [16] = "\uF147", [20] = "\uF148", [24] = "\uF149", [32] = "\uF14C" },
        ["indent-decrease"] = new() { [16] = "\uED22", [20] = "\uED23", [24] = "\uED24" },
        ["indent-increase"] = new() { [16] = "\uED2C", [20] = "\uED2D", [24] = "\uED2E" },
        ["info"] = new() { [16] = "\uF4A2", [20] = "\uF4A3", [24] = "\uF4A4", [32] = "\U000F0059" },
        ["italic"] = new() { [16] = "\uED36", [20] = "\uF7F4", [24] = "\uF7F5" },
        ["journal"] = new() { [16] = "\U000F0388", [20] = "\uF8FD", [24] = "\uF8FE", [32] = "\U000F03D5" },
        ["junk"] = new() { [16] = "\uF705", [20] = "\uF62D", [24] = "\uF62E", [32] = "\U000F01F5" },
        ["language"] = new() { [16] = "\uF4F2", [20] = "\uF4F3", [24] = "\uF4F4" },
        ["layout"] = new() { [16] = "\uE8AF", [20] = "\uE8B0", [24] = "\uE8B1", [32] = "\uEFF6" },
        ["lightbulb"] = new() { [16] = "\uF4D5", [20] = "\uF4D6", [24] = "\uF4D7", [32] = "\uF07D" },
        ["line-spacing"] = new() { [16] = "\U000F0BDC", [20] = "\uF7F6", [24] = "\uF7F7", [32] = "\U000F0BDD" },
        ["link"] = new() { [16] = "\uF4E3", [20] = "\uF4E4", [24] = "\uF4E5", [32] = "\uE771" },
        ["mail"] = new() { [16] = "\uE7A1", [20] = "\uF506", [24] = "\uF507", [32] = "\U000F01F3" },
        ["mail-new"] = new() { [16] = "\uF50D", [20] = "\uF51F", [24] = "\uF50A" },
        ["mark-complete"] = new() { [16] = "\uF297", [20] = "\uF298", [24] = "\uF299", [32] = "\uF8E8" },
        ["meeting"] = new() { [16] = "\uE24D", [20] = "\uE24E", [24] = "\uE24F", [32] = "\uE251" },
        ["message-preview"] = new() { [20] = "\uE8AC" },
        ["month-view"] = new() { [16] = "\U000F0A00", [20] = "\uF22A", [24] = "\uF22B", [32] = "\uEEC3" },
        ["more"] = new() { [16] = "\uE823", [20] = "\uE824", [24] = "\uE825", [32] = "\uE827" },
        ["move"] = new() { [16] = "\uE64B", [20] = "\uE64C", [24] = "\uE64D", [32] = "\U000F0213" },
        ["multilevel-list"] = new() { [16] = "\uF7AD", [20] = "\uF7AE", [24] = "\uF7AF" },
        ["new-items"] = new() { [16] = "\uE4DA", [20] = "\uE4DB", [24] = "\uE4DC" },
        ["new-task"] = new() { [20] = "\uF788", [24] = "\uF789" },
        ["next-7"] = new() { [20] = "\uE26D", [24] = "\uF23F" },
        ["notes"] = new() { [16] = "\uF663", [20] = "\uF56B", [24] = "\uF56C" },
        ["numbering"] = new() { [16] = "\uED3A", [20] = "\uF7F9", [24] = "\uF7FA" },
        ["online-pictures"] = new() { [20] = "\uE722", [24] = "\uE723" },
        ["page-color"] = new() { [16] = "\uF594", [20] = "\uF595", [24] = "\uF596" },
        ["paste"] = new() { [16] = "\uE35A", [20] = "\uF2D5", [24] = "\uF2D6", [32] = "\U000F020B" },
        ["people"] = new() { [16] = "\uF5A7", [20] = "\uF5A8", [24] = "\uF5A9", [32] = "\uE8EC" },
        ["permission"] = new() { [16] = "\uE78E", [20] = "\uE78F", [24] = "\uE790", [32] = "\uE791" },
        ["person-add"] = new() { [16] = "\uE921", [20] = "\uF5C2", [24] = "\uF5C3", [32] = "\U000F044F" },
        ["picture"] = new() { [16] = "\uF487", [20] = "\uF488", [24] = "\uF489", [32] = "\uE719" },
        ["pin"] = new() { [16] = "\uF600", [20] = "\uF601", [24] = "\uF602", [32] = "\uE983" },
        ["print"] = new() { [16] = "\uF6FA", [20] = "\uF62A", [24] = "\uF62B", [32] = "\uE9CD" },
        ["private"] = new() { [16] = "\uE78E", [20] = "\uE78F", [24] = "\uE790", [32] = "\uE791" },
        ["quicksteps"] = new() { [16] = "\U000F05CA", [20] = "\U000F02D6", [24] = "\U000F02D7" },
        ["read-aloud"] = new() { [20] = "\uEB2E", [24] = "\uF6F6" },
        ["reader"] = new() { [20] = "\uF65B", [24] = "\uF65C" },
        ["reading-pane"] = new() { [16] = "\uE8BC", [20] = "\uE8BD", [24] = "\uE8BE", [32] = "\uF000" },
        ["receipt"] = new() { [16] = "\uE7D1", [20] = "\uF521", [24] = "\uF522", [32] = "\U000F0448" },
        ["redo"] = new() { [16] = "\uE0E4", [20] = "\uF16E", [24] = "\uF16F", [32] = "\uF8E6" },
        ["reminder"] = new() { [16] = "\uE014", [20] = "\uF114", [24] = "\uF115", [32] = "\uE015" },
        ["reply"] = new() { [16] = "\uF176", [20] = "\uF177", [24] = "\uF178", [32] = "\U000F0425" },
        ["reply-all"] = new() { [16] = "\uF17A", [20] = "\uF17B", [24] = "\uF17C", [32] = "\U000F0426" },
        ["reverse-sort"] = new() { [16] = "\uF1B3", [20] = "\uF812", [24] = "\uF821" },
        ["rules"] = new() { [16] = "\uE617", [20] = "\uE618", [24] = "\uE619", [32] = "\U000F01CF" },
        ["save"] = new() { [16] = "\uEA43", [20] = "\uF67F", [24] = "\uF680", [32] = "\U000F0579" },
        ["schedule-view"] = new() { [16] = "\U000F0CCB", [20] = "\uF213", [24] = "\uF214" },
        ["search"] = new() { [16] = "\uEA7C", [20] = "\uF68F", [24] = "\uF690", [32] = "\uEA7D" },
        ["send"] = new() { [16] = "\uEA8E", [20] = "\uF699", [24] = "\uF69A", [32] = "\U000F0098" },
        ["send-receive"] = new() { [16] = "\uE110", [20] = "\uF190", [24] = "\uF191" },
        ["settings"] = new() { [16] = "\uF6A8", [20] = "\uF6A9", [24] = "\uF6AA", [32] = "\uEA94" },
        ["shapes"] = new() { [16] = "\uF6AC", [20] = "\uF6AD", [24] = "\uF6AE", [32] = "\U000F03C3" },
        ["share"] = new() { [16] = "\uEAA6", [20] = "\uF6AF", [24] = "\uF6B0", [32] = "\U000F09C0" },
        ["shield"] = new() { [16] = "\uEAC3", [20] = "\uF6BE", [24] = "\uF6BF", [32] = "\uEF20" },
        ["show-progress"] = new() { [16] = "\uF192", [20] = "\uF193", [24] = "\uF194", [32] = "\U000F06AE" },
        ["shrink-font"] = new() { [20] = "\uF437", [24] = "\uF438" },
        ["sign"] = new() { [16] = "\uF0BB", [20] = "\uF27E", [24] = "\uF27F", [32] = "\U000F0469" },
        ["signature"] = new() { [16] = "\uF6DB", [20] = "\uF6DC", [24] = "\uF6DD", [32] = "\U000F023D" },
        ["smart-lookup"] = new() { [20] = "\uF692", [24] = "\uF693" },
        ["smartart"] = new() { [16] = "\uE89B", [20] = "\uF589", [24] = "\uF58A", [32] = "\uE89C" },
        ["snooze"] = new() { [16] = "\uF2DC", [20] = "\uF2DD", [24] = "\uF2DE", [32] = "\uE36E" },
        ["source"] = new() { [16] = "\uF339", [20] = "\uF2EF", [24] = "\uF2F0" },
        ["spacing"] = new() { [20] = "\uE077", [24] = "\uF8CD" },
        ["spelling"] = new() { [16] = "\uED1C", [20] = "\uED1D", [24] = "\uED1E" },
        ["sr-groups"] = new() { [16] = "\uF0E7", [20] = "\U000F0ADE", [24] = "\U000F0ADF", [32] = "\U000F0AE1" },
        ["star"] = new() { [16] = "\uF70E", [20] = "\uF70F", [24] = "\uF710", [32] = "\U000F045E" },
        ["stock-images"] = new() { [16] = "\uE724", [20] = "\uE725", [24] = "\uE726", [32] = "\uE728" },
        ["strikethrough"] = new() { [16] = "\uED5E", [20] = "\uED5F", [24] = "\uED60" },
        ["styles"] = new() { [20] = "\uF7DB", [24] = "\uF7DC" },
        ["subscript"] = new() { [16] = "\uED61", [20] = "\uF806", [24] = "\uF807" },
        ["superscript"] = new() { [16] = "\uED62", [20] = "\uF808", [24] = "\uF809" },
        ["symbol"] = new() { [16] = "\uE7E5", [20] = "\uE7E6", [24] = "\uE7E7", [32] = "\uE7E9" },
        ["table"] = new() { [16] = "\uEBF4", [20] = "\uF75D", [24] = "\uF75E", [32] = "\uEBF6" },
        ["tasks"] = new() { [16] = "\uEFAD", [20] = "\uEC99", [24] = "\uEC9A" },
        ["theme-colors"] = new() { [16] = "\uE3BF", [20] = "\uF2F9", [24] = "\uF2FA", [32] = "\U000F0BCB" },
        ["theme-effects"] = new() { [16] = "\uEE36", [20] = "\uEE37", [24] = "\uEE38" },
        ["themes"] = new() { [16] = "\uE3BC", [20] = "\uF2F5", [24] = "\uF2F6", [32] = "\U000F0CB3" },
        ["thesaurus"] = new() { [16] = "\U000F0388", [20] = "\uF8FD", [24] = "\uF8FE", [32] = "\U000F03D5" },
        ["today"] = new() { [16] = "\uF23B", [20] = "\uF23C", [24] = "\uF23D" },
        ["tracker"] = new() { [16] = "\uE5F4", [20] = "\uE5F5", [24] = "\uE5F6", [32] = "\U000F06D3" },
        ["underline"] = new() { [16] = "\uED67", [20] = "\uF80A", [24] = "\uF80B" },
        ["undo"] = new() { [16] = "\uE126", [20] = "\uF199", [24] = "\uF19A", [32] = "\uE128" },
        ["unread"] = new() { [16] = "\uF525", [20] = "\uF526", [24] = "\uF527", [32] = "\U000F0449" },
        ["update-folder"] = new() { [16] = "\uE663", [20] = "\uE664", [24] = "\uE665" },
        ["view-settings"] = new() { [20] = "\U000F013C", [24] = "\U000F013D" },
        ["voting"] = new() { [16] = "\uE99E", [20] = "\uE99F", [24] = "\uF60D", [32] = "\U000F045A" },
        ["warning"] = new() { [16] = "\uF868", [20] = "\uF869", [24] = "\uF86A", [32] = "\U000F024A" },
        ["week-view"] = new() { [20] = "\uF240", [24] = "\uF241" },
        ["word-count"] = new() { [20] = "\uF80C", [24] = "\uF80D" },
        ["work-offline"] = new() { [16] = "\U000F0394", [20] = "\uF609", [24] = "\uF60A" },
        ["work-week"] = new() { [16] = "\uF243", [20] = "\uF244", [24] = "\uF245", [32] = "\U000F09D6" },
        ["zoom"] = new() { [16] = "\uEE8E", [20] = "\uF8C4", [24] = "\uF8C5", [32] = "\U000F09F1" },
        ["zoom-in"] = new() { [16] = "\uF108", [20] = "\uF109", [24] = "\uF10A", [32] = "\uF58D" },
        ["zoom-out"] = new() { [16] = "\uEBCF", [20] = "\uEBD0", [24] = "\uEBD1" },
    };

    public static IReadOnlyCollection<string> Names => Map.Keys;

    public static bool Has(string name) => Map.ContainsKey(name);

    /// <summary>
    /// The glyph for a logical name at the nearest available size, rounding down so a request
    /// never returns artwork drawn with more detail than the target can show.
    /// </summary>
    public static string Get(string name, int size = 20)
    {
        if (!Map.TryGetValue(name, out var bySize))
        {
            throw new KeyNotFoundException(
                $"No icon named '{name}'. Add it to tools/generate-icons.py and regenerate.");
        }

        if (bySize.TryGetValue(size, out var exact)) return exact;

        var best = bySize.Keys.Where(s => s <= size).DefaultIfEmpty(bySize.Keys.Min()).Max();
        return bySize[best];
    }

    /// <summary>Never throws. Returns an empty string for an unknown name.</summary>
    public static string GetOrEmpty(string name, int size = 20)
        => Map.ContainsKey(name) ? Get(name, size) : string.Empty;
}
