// <auto-generated>
//   Generated from the Fluent UI System Icons metadata (MIT, microsoft/fluentui-system-icons).
//   Regenerate with tools/generate-icons.py rather than editing by hand.
// </auto-generated>

namespace Mailbox.Theming.Icons;

/// <summary>
/// Maps Mailbox's logical icon names onto glyphs in the bundled Fluent UI System Icons font.
/// </summary>
/// <remarks>
/// Commands reference icons by logical name, never by codepoint, so a theme can swap the whole
/// icon set without touching a single command definition.
/// <para>
/// Fluent ships separately drawn artwork per size rather than one outline scaled up — a 16px
/// glyph carries less detail than its 24px sibling by design. Asking for the size you will
/// actually render at is what keeps icons crisp.
/// </para>
/// </remarks>
public static class IconGlyphs
{
    /// <summary>Sizes the bundled font provides artwork for.</summary>
    public static readonly int[] Sizes = [16, 20, 24, 32];

    // Values are strings rather than chars: Fluent places some glyphs in supplementary
    // private-use planes above U+FFFF, which do not fit in a 16-bit char and need a
    // surrogate pair.
    private static readonly Dictionary<string, Dictionary<int, string>> Map =
        new(StringComparer.OrdinalIgnoreCase)
    {
        ["add"] = new() { [16] = "\uF108", [20] = "\uF109", [24] = "\uF10A", [32] = "\uF58D" },
        ["address-book"] = new() { [16] = "\U000F09AD", [20] = "\uE16A", [24] = "\uE16B", [32] = "\uE16D" },
        ["apps"] = new() { [16] = "\uE6C3", [20] = "\uF462", [24] = "\uF463" },
        ["archive"] = new() { [16] = "\uF8CC", [20] = "\uF139", [24] = "\uF13A", [32] = "\uE066" },
        ["arrange"] = new() { [16] = "\uF1AB", [20] = "\uF18A", [24] = "\uF18B" },
        ["attach"] = new() { [16] = "\uF1A8", [20] = "\uF1A9", [24] = "\uF1AA", [32] = "\U000F0427" },
        ["avatar"] = new() { [16] = "\U000F0B55", [20] = "\uE928", [24] = "\uE929", [32] = "\uF042" },
        ["calendar"] = new() { [16] = "\uE24D", [20] = "\uE24E", [24] = "\uE24F", [32] = "\uE251" },
        ["cancel"] = new() { [16] = "\uF36C", [20] = "\uF36D", [24] = "\uF36E", [32] = "\uE4C3" },
        ["categorize"] = new() { [16] = "\uEC70", [20] = "\uF77C", [24] = "\uF77D", [32] = "\uEC72" },
        ["change-view"] = new() { [16] = "\U000F02A4", [20] = "\uF18D", [24] = "\uF18E" },
        ["chevron-down"] = new() { [16] = "\uF2A2", [20] = "\uF2A3", [24] = "\uF2A4", [32] = "\U000F0320" },
        ["chevron-left"] = new() { [16] = "\uF2A9", [20] = "\uF2AA", [24] = "\uF2AB", [32] = "\U000F0321" },
        ["chevron-right"] = new() { [16] = "\uF2AF", [20] = "\uF2B0", [24] = "\uF2B1", [32] = "\U000F0322" },
        ["chevron-up"] = new() { [16] = "\uF2B5", [20] = "\uF2B6", [24] = "\uF2B7", [32] = "\U000F0323" },
        ["cleanup"] = new() { [16] = "\uF1FE", [20] = "\uF201", [24] = "\uF202", [32] = "\U000F0429" },
        ["collapse-left"] = new() { [16] = "\uF2A9", [20] = "\uF2AA", [24] = "\uF2AB", [32] = "\U000F0321" },
        ["day-view"] = new() { [16] = "\uE244", [20] = "\uF222", [24] = "\uF223", [32] = "\U000F09D5" },
        ["delete"] = new() { [16] = "\uE47B", [20] = "\uF34C", [24] = "\uF34D", [32] = "\uEEA6" },
        ["dismiss"] = new() { [16] = "\uF368", [20] = "\uF369", [24] = "\uF36A", [32] = "\uF3F3" },
        ["dock"] = new() { [16] = "\uF581", [20] = "\uF582", [24] = "\uF583", [32] = "\uF667" },
        ["expand-right"] = new() { [16] = "\uF2AF", [20] = "\uF2B0", [24] = "\uF2B1", [32] = "\U000F0322" },
        ["filter"] = new() { [16] = "\uE60A", [20] = "\uF406", [24] = "\uF407", [32] = "\U000F0432" },
        ["flag"] = new() { [16] = "\uF40A", [20] = "\uF40B", [24] = "\uF40C", [32] = "\U000F003C" },
        ["focus-time"] = new() { [16] = "\uF4D5", [20] = "\uF4D6", [24] = "\uF4D7", [32] = "\uF07D" },
        ["folder"] = new() { [16] = "\uE643", [20] = "\uF418", [24] = "\uF419", [32] = "\uE644" },
        ["folder-open"] = new() { [16] = "\uF42D", [20] = "\uF42E", [24] = "\uF42F" },
        ["forward"] = new() { [16] = "\uF156", [20] = "\uF157", [24] = "\uF158", [32] = "\U000F0424" },
        ["ignore"] = new() { [16] = "\uF36C", [20] = "\uF36D", [24] = "\uF36E", [32] = "\uE4C3" },
        ["importance"] = new() { [16] = "\uF49E", [20] = "\uF49F", [24] = "\uF4A0", [32] = "\U000F0444" },
        ["info"] = new() { [16] = "\uF4A2", [20] = "\uF4A3", [24] = "\uF4A4", [32] = "\U000F0059" },
        ["journal"] = new() { [16] = "\U000F0388", [20] = "\uF8FD", [24] = "\uF8FE", [32] = "\U000F03D5" },
        ["junk"] = new() { [16] = "\uF705", [20] = "\uF62D", [24] = "\uF62E", [32] = "\U000F01F5" },
        ["layout"] = new() { [16] = "\uE8AF", [20] = "\uE8B0", [24] = "\uE8B1", [32] = "\uEFF6" },
        ["mail"] = new() { [16] = "\uE7A1", [20] = "\uF506", [24] = "\uF507", [32] = "\U000F01F3" },
        ["mail-new"] = new() { [16] = "\uF50D", [20] = "\uF51F", [24] = "\uF50A" },
        ["mark-complete"] = new() { [16] = "\uF297", [20] = "\uF298", [24] = "\uF299", [32] = "\uF8E8" },
        ["meeting"] = new() { [16] = "\uE24D", [20] = "\uE24E", [24] = "\uE24F", [32] = "\uE251" },
        ["message-preview"] = new() { [20] = "\uE8AC" },
        ["month-view"] = new() { [16] = "\U000F0A00", [20] = "\uF22A", [24] = "\uF22B", [32] = "\uEEC3" },
        ["more"] = new() { [16] = "\uE823", [20] = "\uE824", [24] = "\uE825", [32] = "\uE827" },
        ["move"] = new() { [16] = "\uE64B", [20] = "\uE64C", [24] = "\uE64D", [32] = "\U000F0213" },
        ["new-items"] = new() { [16] = "\uE4DA", [20] = "\uE4DB", [24] = "\uE4DC" },
        ["new-task"] = new() { [20] = "\uF788", [24] = "\uF789" },
        ["next-7"] = new() { [20] = "\uE26D", [24] = "\uF23F" },
        ["notes"] = new() { [16] = "\uF663", [20] = "\uF56B", [24] = "\uF56C" },
        ["people"] = new() { [16] = "\uF5A7", [20] = "\uF5A8", [24] = "\uF5A9", [32] = "\uE8EC" },
        ["pin"] = new() { [16] = "\uF600", [20] = "\uF601", [24] = "\uF602", [32] = "\uE983" },
        ["print"] = new() { [16] = "\uF6FA", [20] = "\uF62A", [24] = "\uF62B", [32] = "\uE9CD" },
        ["private"] = new() { [16] = "\uE78E", [20] = "\uE78F", [24] = "\uE790", [32] = "\uE791" },
        ["quicksteps"] = new() { [16] = "\U000F05CA", [20] = "\U000F02D6", [24] = "\U000F02D7" },
        ["read-aloud"] = new() { [20] = "\uEB2E", [24] = "\uF6F6" },
        ["reader"] = new() { [20] = "\uF65B", [24] = "\uF65C" },
        ["reading-pane"] = new() { [16] = "\uE8BC", [20] = "\uE8BD", [24] = "\uE8BE", [32] = "\uF000" },
        ["redo"] = new() { [16] = "\uE0E4", [20] = "\uF16E", [24] = "\uF16F", [32] = "\uF8E6" },
        ["reminder"] = new() { [16] = "\uE014", [20] = "\uF114", [24] = "\uF115", [32] = "\uE015" },
        ["reply"] = new() { [16] = "\uF176", [20] = "\uF177", [24] = "\uF178", [32] = "\U000F0425" },
        ["reply-all"] = new() { [16] = "\uF17A", [20] = "\uF17B", [24] = "\uF17C", [32] = "\U000F0426" },
        ["reverse-sort"] = new() { [16] = "\uF1B3", [20] = "\uF812", [24] = "\uF821" },
        ["rules"] = new() { [16] = "\uE617", [20] = "\uE618", [24] = "\uE619", [32] = "\U000F01CF" },
        ["schedule-view"] = new() { [16] = "\U000F0CCB", [20] = "\uF213", [24] = "\uF214" },
        ["search"] = new() { [16] = "\uEA7C", [20] = "\uF68F", [24] = "\uF690", [32] = "\uEA7D" },
        ["send"] = new() { [16] = "\uEA8E", [20] = "\uF699", [24] = "\uF69A", [32] = "\U000F0098" },
        ["send-receive"] = new() { [16] = "\uE110", [20] = "\uF190", [24] = "\uF191" },
        ["settings"] = new() { [16] = "\uF6A8", [20] = "\uF6A9", [24] = "\uF6AA", [32] = "\uEA94" },
        ["share"] = new() { [16] = "\uEAA6", [20] = "\uF6AF", [24] = "\uF6B0", [32] = "\U000F09C0" },
        ["shield"] = new() { [16] = "\uEAC3", [20] = "\uF6BE", [24] = "\uF6BF", [32] = "\uEF20" },
        ["show-progress"] = new() { [16] = "\uF192", [20] = "\uF193", [24] = "\uF194", [32] = "\U000F06AE" },
        ["snooze"] = new() { [16] = "\uF2DC", [20] = "\uF2DD", [24] = "\uF2DE", [32] = "\uE36E" },
        ["source"] = new() { [16] = "\uF339", [20] = "\uF2EF", [24] = "\uF2F0" },
        ["spacing"] = new() { [20] = "\uE077", [24] = "\uF8CD" },
        ["sr-groups"] = new() { [16] = "\uF0E7", [20] = "\U000F0ADE", [24] = "\U000F0ADF", [32] = "\U000F0AE1" },
        ["star"] = new() { [16] = "\uF70E", [20] = "\uF70F", [24] = "\uF710", [32] = "\U000F045E" },
        ["tasks"] = new() { [16] = "\uEFAD", [20] = "\uEC99", [24] = "\uEC9A" },
        ["today"] = new() { [16] = "\uF23B", [20] = "\uF23C", [24] = "\uF23D" },
        ["tracker"] = new() { [16] = "\uE5F4", [20] = "\uE5F5", [24] = "\uE5F6", [32] = "\U000F06D3" },
        ["undo"] = new() { [16] = "\uE126", [20] = "\uF199", [24] = "\uF19A", [32] = "\uE128" },
        ["unread"] = new() { [16] = "\uF525", [20] = "\uF526", [24] = "\uF527", [32] = "\U000F0449" },
        ["update-folder"] = new() { [16] = "\uE663", [20] = "\uE664", [24] = "\uE665" },
        ["view-settings"] = new() { [20] = "\U000F013C", [24] = "\U000F013D" },
        ["warning"] = new() { [16] = "\uF868", [20] = "\uF869", [24] = "\uF86A", [32] = "\U000F024A" },
        ["week-view"] = new() { [20] = "\uF240", [24] = "\uF241" },
        ["work-offline"] = new() { [16] = "\U000F0394", [20] = "\uF609", [24] = "\uF60A" },
        ["work-week"] = new() { [16] = "\uF243", [20] = "\uF244", [24] = "\uF245", [32] = "\U000F09D6" },
        ["zoom-in"] = new() { [16] = "\uF108", [20] = "\uF109", [24] = "\uF10A", [32] = "\uF58D" },
        ["zoom-out"] = new() { [16] = "\uEBCF", [20] = "\uEBD0", [24] = "\uEBD1" },
    };

    public static IReadOnlyCollection<string> Names => Map.Keys;

    public static bool Has(string name) => Map.ContainsKey(name);

    /// <summary>
    /// The glyph for a logical name at the nearest available size, rounding down so a request
    /// never returns artwork drawn with more detail than the target can show.
    /// </summary>
    public static string Get(string name, int size = 20)
    {
        if (!Map.TryGetValue(name, out var bySize))
        {
            throw new KeyNotFoundException(
                $"No icon named '{name}'. Add it to tools/generate-icons.py and regenerate.");
        }

        if (bySize.TryGetValue(size, out var exact)) return exact;

        var best = bySize.Keys.Where(s => s <= size).DefaultIfEmpty(bySize.Keys.Min()).Max();
        return bySize[best];
    }

    /// <summary>Never throws. Returns an empty string for an unknown name.</summary>
    public static string GetOrEmpty(string name, int size = 20)
        => Map.ContainsKey(name) ? Get(name, size) : string.Empty;
}
